export enum CloudErrorType {
    SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',
    DATABASE_DUPLICATE = 'DATABASE_DUPLICATE',
    DATABASE_INSERT = 'DATABASE_INSERT',
    DATABASE_DELETE = 'DATABASE_DELETE',
    WEBDAV_MOVE = 'WEBDAV_MOVE',
    WEBDAV_DELETE = 'WEBDAV_DELETE'
}
