export enum SyncErrorType {
    SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',
    DATABASE_DUPLICATE = 'DATABASE_DUPLICATE',
    DATABASE_INSERT = 'DATABASE_INSERT',
    WEBDAV_MOVE = 'WEBDAV_MOVE'
}
